# Generated by Django 5.2.8 on 2026-06-21 15:55

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('japanese_translation', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LexicalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headword', models.CharField(max_length=255, unique=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['headword'],
            },
        ),
        migrations.CreateModel(
            name='SituationFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='expressions.situationframe')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpressionSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_links', to='expressions.expression')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expression_links', to='expressions.situationframe')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='expression',
            name='situations',
            field=models.ManyToManyField(blank=True, related_name='expressions', through='expressions.ExpressionSituation', to='expressions.situationframe'),
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=255)),
                ('explanation', models.TextField(blank=True)),
                ('example', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lexical_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='expressions.lexicalitem')),
            ],
            options={
                'ordering': ['lexical_item__headword', 'meaning'],
            },
        ),
        migrations.CreateModel(
            name='ExpressionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_links', to='expressions.expression')),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expression_links', to='expressions.usage')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='expression',
            name='usages',
            field=models.ManyToManyField(blank=True, related_name='expressions', through='expressions.ExpressionUsage', to='expressions.usage'),
        ),
        migrations.CreateModel(
            name='SearchAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lexical_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_aliases', to='expressions.lexicalitem')),
            ],
            options={
                'verbose_name_plural': 'search aliases',
                'ordering': ['text'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('text'), name='unique_search_alias_text_ci')],
            },
        ),
        migrations.AddConstraint(
            model_name='situationframe',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_situation_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='expressionsituation',
            constraint=models.UniqueConstraint(fields=('expression', 'situation'), name='unique_expression_situation'),
        ),
        migrations.AddConstraint(
            model_name='usage',
            constraint=models.UniqueConstraint(fields=('lexical_item', 'meaning'), name='unique_usage_meaning_per_lexical_item'),
        ),
        migrations.AddConstraint(
            model_name='expressionusage',
            constraint=models.UniqueConstraint(fields=('expression', 'usage'), name='unique_expression_usage'),
        ),
    ]
