# Generated by Django 5.2.8 on 2026-06-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expressions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexicalitem',
            name='item_type',
            field=models.CharField(choices=[('word', '単語'), ('phrase', '熟語'), ('chunk', 'チャンク')], default='word', max_length=20),
        ),
    ]
