# Generated by Django 5.2.8 on 2026-06-21 16:15

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expressions', '0002_lexicalitem_item_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='situationframe',
            name='unique_situation_name_per_parent',
        ),
        migrations.AddField(
            model_name='expressionusage',
            name='surface_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lexicalitem',
            name='headword',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='lexicalitem',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('headword'), name='unique_lexical_item_headword_ci'),
        ),
        migrations.AddConstraint(
            model_name='situationframe',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_situation_name_per_parent', nulls_distinct=False),
        ),
    ]
